### ISSUE TITLE
Awesome initiative 👏🏽 

### ISSUE THREAD

**Issue by juliohm** [alex-s-gardner/FastGeoProjections.jl#17]
Finally a pure Julia implementation that I can start contributing to! 🎉 

@alex-s-gardner we are about to start some work in Meshes.jl to add geodetic and cartographic projections. It would be nice to understand what is your long-term plan regarding the Proj.jl dependency. Any chance that it could be dropped? My understanding is that people who need Proj.jl will end up using it directly, and people who love pure Julia will avoid taking the package as a dependency.

If the dependency can be dropped, we can consider adding FastGeoProjections.jl as a dependency in Meshes.jl. I would be happy to join efforts on this initiative.

**Comment by juliohm** [comment]
Also, if you can shed some light on the differences between FastGeoProjections.jl and Geodesy.jl, that would be great.

**Comment by alex-s-gardner** [comment]
> long-term plan regarding the Proj.jl dependency

The Proj.jl dependency is purely included for connivance. FastGeoProjections.jl is only intended to support the most popular geographic projections so that it can stay keenly focused on performance. I personally don't care for the dependance but it can be very convenient for users of FastGeoProjections.jl that would like to use the FGP implementation when available and fall back to Proj.jl when non exists. Part of the goal of FGP is to minimize any burden on the user.

I think the path forward to include Proj.jl support as an extension, getting the best of both worlds.

**Comment by juliohm** [comment]
The extension idea sounds great. What about the differences with the existing Geodesy.jl? You found some design issue with the package? What is the motivation to start this new effort here? Speed?

**Comment by alex-s-gardner** [comment]
> differences between FastGeoProjections.jl and Geodesy.jl

FastGeoProjections.jl is keenly focused on ease of use and speed (LoopVectorization).

Geodesy.jl is a pure julia implementation of UTM, Geographic, and ECEF with support for multiple Datums. 

Geodesy.jl as it's name suggests is more geodesy (shape of earth) focused while FGP is light weight and focuses on fast transformation from and to the most commonly used coordinate reference systems. Since most modern coordinate reference systems are referenced to the WGS84 ellipsoid FGP currently only supports 2-D (x,y) transformations... though if there is demand, support for 3-D transformations can be added to support other datums.

FGP = simple, fast, targeted
Geodesy.jl  = more extensive and datum and reference frame focused.

**Comment by alex-s-gardner** [comment]
> FastGeoProjections.jl as a dependency in Meshes.jl

This would be really fantastic and a direction that I think @rafaqz would be keen to see happen
